version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ViewContext=Server=database,1433;Database=views;User Id=sa;Password=Pass@word
    build:
      context: ./backend
      # dockerfile: Bomp.Api/Dockerfile.develop
  client:
    volumes:
      - ./frontend/PokeProj/src:/app/src
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend/PokeProj
      # dockerfile: Dockerfile.develop