version: '3.8'

services:
  backend:
    image: bomp.api:latest
    build:
      context: ./backend/Bomp.Api
    ports:
      - 5000:80
  client:
    image: pokeproj:latest
    build:
      context: ./frontend/PokeProj
    ports:
      - 4000:80
