name: Dotnet Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - run: dotnet build src/backend
      - run: dotnet test src/backend