FROM mcr.microsoft.com/dotnet/sdk:5.0

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y procps

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
WORKDIR /app/Bomp.Api
ENTRYPOINT dotnet restore && dotnet watch run --urls=http://+:80
